apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- persistent-volume-claim.yml
- service.yml
commonLabels:
  app.kubernetes.io/name: mosquitto
  app: mosquitto
configMapGenerator:
- name: mosquitto-base-config
  files:
  - mosquitto.conf
  - password_file
