---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquitto-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquitto-conf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
